// Runtime is bundled so plugin installation needs no npm install.
import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
await build({
  stdin: { contents: `export {default as Ajv} from 'ajv'; export {default as Ajv2019} from 'ajv/dist/2019.js'; export {default as Ajv2020} from 'ajv/dist/2020.js'; export {default as addFormats} from 'ajv-formats'; export {parse as parseYaml} from 'yaml'; export {default as JSON5} from 'json5';`, resolveDir: process.cwd() },
  outfile: 'src/vendor/validation.js', bundle: true, platform: 'node', format: 'esm', minify: true,
  banner: { js: '// Generated by npm run build:vendor. See THIRD_PARTY_LICENSES.txt.\nimport {createRequire} from \"node:module\"; const require = createRequire(import.meta.url);' },
});
const packages = ['ajv', 'ajv-formats', 'fast-deep-equal', 'fast-uri', 'json-schema-traverse', 'require-from-string', 'yaml', 'json5'];
let notices = '';
for (const name of packages) {
  const root = `node_modules/${name}`;
  const pkg = JSON.parse(await readFile(`${root}/package.json`, 'utf8'));
  let license;
  for (const file of ['LICENSE', 'LICENSE.md']) {
    try { license = await readFile(`${root}/${file}`, 'utf8'); break; } catch {}
  }
  if (!license) throw new Error(`Missing license for ${name}`);
  notices += `${name}@${pkg.version}\n${license}\n\n`;
}
await writeFile('src/vendor/THIRD_PARTY_LICENSES.txt', notices);
